# Generated by Django 3.2.12 on 2023-04-14 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.comment'),
        ),
        migrations.AlterField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(related_name='like_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
